# Generated by Django 4.2.8 on 2024-07-10 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_bookevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=700)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.work')),
            ],
        ),
    ]
